version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  groups:
    action-dependencies:
      patterns:
        - "*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  groups:
    angular-dependencies:
      patterns:
        - "@angular*"
    ngrx-dependencies:
      patterns:
        - "@ngrx*"
    type-dependencies:
      patterns:
        - "@types*"
    npm-dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "@angular*"
        - "@ngrx*"
        - "@types*"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  groups:
    docker-dependencies:
      patterns:
        - "*"
