# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint application code
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v1

      - name: Use Node.js 13.10.1
        uses: actions/setup-node@v1
        with:
          node-version: 13.10.1

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn lint`
        run: yarn lint

  lint-documentation:
    name: Lint documentation files
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v1

      - name: Lint `README.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './README.md'

      - name: Lint `doc/COMMANDS.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/COMMANDS.md'

      - name: Lint `doc/CONCEPTS_AND_FEATURES.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/CONCEPTS_AND_FEATURES.md'

      - name: Lint `doc/SPEED_UP_DOCKER_COMPOSE.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/SPEED_UP_DOCKER_COMPOSE.md'

      - name: Lint `doc/TOOLS.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/TOOLS.md'

      - name: Lint `doc/USAGE_CHECKLIST.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/USAGE_CHECKLIST.md'

  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v1

      - name: Use Node.js 13.10.1
        uses: actions/setup-node@v1
        with:
          node-version: 13.10.1

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn build-prod`
        run: yarn build-prod
