# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-typescript:
    name: Lint application code
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.0

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn lint:ts`
        run: yarn lint:ts

  lint-scss:
    name: Lint application SCSS files
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.0

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn lint:scss`
        run: yarn lint:scss

  lint-documentation:
    name: Lint documentation files
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Lint `./README.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './README.md'

      - name: Lint all the resource docs under `./doc/` directory
        uses: avto-dev/markdown-lint@v1
        with:
          config: './markdown-lint.yml'
          args: './doc/*.md'

  check-translations:
    name: Check that translations are up-to-date
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.0

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn run extract-translations && git diff --exit-code`
        run: yarn run extract-translations && git diff --exit-code

  check-untranslated-text-tags:
    name: Check that there are no untranslated text tags
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.0

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn run check-translations`
        run: yarn run check-translations

  build:
    name: Build application Docker image
    runs-on: ubuntu-latest
    needs:
      - lint-typescript
      - lint-scss
      - lint-documentation
      - check-translations
      - check-untranslated-text-tags

    steps:
      - name: Make checkout
        uses: actions/checkout@v4

      - name: Set tag var
        id: vars
        run: echo "DOCKER_TAG=$(echo ${GITHUB_REF} | sed -r 's/[\/()\.]+/_/g')-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag angular-ngrx-frontend:${{ steps.vars.outputs.DOCKER_TAG }}
